name: "deploy code"

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  # defined as a variable in order to be repository-dependent
  CONFIG_FILE_URL: ${{ vars.CALENDARS_JSON }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check for config file
        if: ${{env.CONFIG_FILE_URL == ''}}
        run: |
          echo "No CALENDARS_JSON variable !"
          exit 1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - run: yarn --frozen-lockfile --non-interactive

      - name: build
        run: |
          printf '"%s"' "$CONFIG_FILE_URL"  >src/utils/configUrl.json
          yarn build
          mkdir build
          cp -r css index.html dist img LICENSE freerooms.html favicon.ico -t build
          
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4